on:
  push:
    branches:
      - $default-branch
    paths:
      - src/**
      - migrations/committed/**
      - Dockerfile
      - package-lock.json
      - schema.graphql
name: Docker Image
jobs:
  docker:
    uses: compada/compada/.github/workflows/docker_image.yml@main
