on:
  push:
    branches:
      - $default-branch
    paths-ignore:
      - 'deploy/**'
      - '.github/**'
name: Docker Image
jobs:
  docker:
    uses: compada/compada/.github/workflows/docker_image.yml@main
